# Generated by Django 4.2.11 on 2024-04-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.CharField(choices=[('AL', 'Обо всем'), ('PL', 'Политика'), ('SC', 'Наука'), ('TE', 'Технологии'), ('AR', 'Искусство'), ('SP', 'Космос')], default='AL', max_length=2),
        ),
    ]
