# Generated by Django 4.2.11 on 2024-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_post_postcategory_post_postcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.CharField(choices=[('AL', 'Обо всем'), ('PL', 'Политика'), ('SC', 'Наука'), ('TE', 'Технологии'), ('AR', 'Искусство'), ('SP', 'Космос')], default='AL', max_length=2),
        ),
    ]
