# Generated by Django 4.2.11 on 2024-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
